### ISSUE TITLE
GroupBinding

### ISSUE THREAD

**Issue by crivero7** [rack-io/rackio-framework#3]
Bro, please check the direction='write' for GroupBinding. Once you set a group and then you invoke it as direction='Write'
state_machine:'Group' object has no attribute 'tag'

**Comment by rack-io** [comment]
Thanks for reaching, we saw the problem with this, we had to initialize first the Group instance in order to perform a write operation on the Tag Engine, if a state machine did not define a group attribute then in can not perform proper write. Thanks
